services:
  tf2-mge:
    image: avanavan/docker-tf2mge:latest
    container_name: mge
    restart: unless-stopped
    # Map it or bind it to host
    ports:
      - "27015:27015/udp"
      - "27015:27015/tcp"
      - "27020:27020/udp"
    # network_mode: "host"

    environment:
      - HOSTNAME=Docker MGE Server
      - MGE_MAP=mge_training_v8_beta4b
      - SV_PASSWORD=dockermge
      - RCON_PASSWORD=changeme123
      - SV_DOWNLOADURL=https://fastdl.serveme.tf/
      - SB_WEBHOOK=
      - TV_NAME=DockerTV
      
      # SourceBans Database (optional - leave empty for no database)
      - DB_SB_HOST=
      - DB_SB_PORT=3306
      - DB_SB_NAME=
      - DB_SB_USR=
      - DB_SB_PW=
      
      # MGE Database (optional - will use SQLite if not specified)
      - DB_MGE_HOST=
      - DB_MGE_PORT=3306
      - DB_MGE_NAME=
      - DB_MGE_USR=
      - DB_MGE_PW=
    volumes:
      # Optional, bind mount
      - ./tf2-data:/home/tf2/hlserver/tf2/tf
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      # - WATCHTOWER_RUN_ONCE=true # debug
      - WATCHTOWER_POLL_INTERVAL=3600  # Seconds (1 hr)
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true