name: push-image

# CREDIT: https://codeberg.org/spire/docker-comp-server/src/branch/master/.forgejo/workflows/docker.yaml

on:
    push:
        branches:
        - "main"
        paths:
        - "*.sh"
        - "*.yaml"
        - "*.cfg"
        - "*.txt"
        - "Dockerfile"
    workflow_dispatch:
    repository_dispatch:
        types: [build]

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: avanavan/docker-tf2mge:latest
        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}